url_azure: https://dev.azure.com/axityswd
token_azure: 
name_pool_azure: Axity-Pool
user_name_vm: adminuser
agent_url_download: https://vstsagentpackage.azureedge.net/agent/3.220.2/vsts-agent-linux-x64-3.220.2.tar.gz
agent_name_tar: vsts-agent-linux-x64-3.220.2.tar.gz