---
- name: Install Docker on Ubuntu
  hosts: all
  tasks:
    - name: Download Docker install script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh

    - name: Show Docker install steps
      command: sh /tmp/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Install Docker
      shell: sh /tmp/get-docker.sh

    - name: Install uidmap
      apt:
        name: uidmap
        state: present
        update_cache: yes

    - name: Set permissions for /var/run/docker.sock
      shell: sudo chmod o+rw /var/run/docker.sock

    - name: Install unzip tool
      apt:
        name: unzip
        state: present
        update_cache: yes

    # - name: Unzip a file unarchive:
    #   src: /path/to/your/source/file.zip
    #   dest: /path/where/you/want/to/extract
    #   remote_src: yes
